// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 35);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "1d8e7da9-18b7-44ed-9846-38272cf3bdc1");
user_pref("calendar.registry.1d8e7da9-18b7-44ed-9846-38272cf3bdc1.calendar-main-in-composite", true);
user_pref("calendar.registry.1d8e7da9-18b7-44ed-9846-38272cf3bdc1.disabled", true);
user_pref("calendar.registry.1d8e7da9-18b7-44ed-9846-38272cf3bdc1.name", "Home");
user_pref("calendar.registry.1d8e7da9-18b7-44ed-9846-38272cf3bdc1.type", "storage");
user_pref("calendar.registry.1d8e7da9-18b7-44ed-9846-38272cf3bdc1.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Nairobi");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1638185651204");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210528153351");
user_pref("extensions.lastAppVersion", "78.11.0");
user_pref("extensions.lastPlatformVersion", "78.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"f45ecf29-889e-4a51-9d9b-80f2a2fe7347\",\"default-theme@mozilla.org\":\"b28df8b4-3e57-455c-9f7d-51af79068474\",\"google@search.mozilla.org\":\"e36878dc-268d-4fe6-9e49-d856e9280355\",\"amazondotcom@search.mozilla.org\":\"cd1f3147-a6c7-47ab-8d89-230695bd5dc7\",\"bing@search.mozilla.org\":\"23ec3878-dd91-42f4-9e5e-884a6d6934dd\",\"ddg@search.mozilla.org\":\"b52870ad-59ab-4785-8884-6448510ccde0\",\"wikipedia@search.mozilla.org\":\"4928a5fa-67da-4901-a1c7-a95794f3bf48\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "e37dd35b-b3e5-4993-aa31-00c0baba553");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "e96f652f-90d7-4016-99ef-c19a981e1196");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "af9380d6-5c13-440a-82b9-88bdb987dfd7");
user_pref("toolkit.telemetry.previousBuildID", "20210528153351");
